# default motd is the motd that shows to unregistered players
# the motd for registered players is in players.yml or in your mysql database
# PLAYER put this on motd to put the name of player
# use colors with &a &b ... in motd
# for the second line use \n in motd
# on ip is the ip of the MySQL
# the use is true for use the mysql or false to use player.yml
mysql:
  use: false
  ip: 127.0.0.1
  database: datafile
  user: sqluser
  password: sqlpass
  port: 3306
defaultmotd: "&aWelcome Player \n&bto the Server"
