name: LoginMeIn
main: com.craftilandia.loginmein.Main
version: 6
author: raton023
website: http://dev.bukkit.org/bukkit-plugins/loginmein/
commands:
    login:
        usage: /login <password>
        description: Login using your password
    register:
        usage: /register <password>
        description: Register your player name
    changepass:
        usage: /changepass player <password> <newpassword>
        description: Change your password
    unregister:
        usage: /unregister player <password>
        description: unregister your player name
    setemail:
        usage: /setemail <password>
        description: set your email for recover passwords
    forgotpass:
        usage: /forgotpass
        description: send your password to the registered email
