name: logmein
main: com.craftilandia.loginmein.Main
version: 3.0
commands:
    login:
        usage: /login <password>
        description: Login using your password
    register:
        usage: /register <password>
        description: Register your player name
    changepass:
        usage: /changepass <password> <newpassword>
        description: Change your password
    unregister:
        usage: /unregister <password>
        description: unregister your player name
