name: LoginMeIn
main: com.craftilandia.loginmein.Main
version: 4.0
commands:
    login:
        usage: /login <password>
        description: Login using your password
    register:
        usage: /register <password>
        description: Register your player name
    changepass:
        usage: /changepass PLAYER <password> <newpassword>
        description: Change your password
    unregister:
        usage: /unregister PLAYER <password>
        description: unregister your player name
